# Kubernetes Deployment manifest for NGINX static website
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-website
  labels:
    app: nginx-static
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      imagePullSecrets:
      - name: acr-auth
      containers:
      - name: nginx
        image: mycompany/nginx-static-website:1.0.0
        ports:
        - containerPort: 80
