# Kubernetes Service manifest exposing NGINX deployment
apiVersion: v1
kind: Service
metadata:
  name: static-nginx-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: static-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
